version: "2.2"
services:
  jobmanager:
    image: flink:1.19.0-scala_2.12
    ports:
      - "8081:8081"
    # command: standalone-job --foreground --job-classname WordCount --jars /opt/flink/usrlib/wordcount_2.12-1.0.jar 
    command: jobmanager
    volumes:
      - /Users/ravitejasagiraju/flink/usrlib:/opt/flink/usrlib
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        jobmanager.rpc.port: 6123
        jobmanager.heap.size: 256mb
        jobmanager.memory.process.size: 1024mb    
        parallelism.default: 2   

  taskmanager:
    image: flink:1.19.0-scala_2.12
    depends_on:
      - jobmanager
    command: taskmanager
    scale: 1
    volumes:
      - /Users/ravitejasagiraju/flink/usrlib:/opt/flink/usrlib
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 2
        parallelism.default: 2 
    # stop_grace_period: 10s